# -*- coding: utf-8 -*-
"""Refactored_Data_Toolkit.ipynb

Automatically generated by Colab.
"""

import io
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from google.colab import files
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, OneHotEncoder, OrdinalEncoder

class DataRefiner:
    """
    A comprehensive utility class for preprocessing, auditing, 
    and visualizing datasets directly within Jupyter/Colab notebooks.
    """
    def __init__(self):
        self.data_frame = None
        self.num_fields = []
        self.cat_fields = []

    # === 1. FILE IMPORT & PREPARATION ===
    def import_local_csv(self):
        """Triggers a file upload dialog for local CSV ingestion."""
        print("Awaiting CSV file upload...")
        uploaded_files = files.upload()
        
        if not uploaded_files:
            print("Upload cancelled or failed.")
            return

        csv_name = list(uploaded_files.keys())[0]
        
        # Standardize common missing value representations during import
        null_markers = ['?', '$n/a$', 'n/a', 'N/A', 'NULL', 'null', ' ']
        self.data_frame = pd.read_csv(io.BytesIO(uploaded_files[csv_name]), na_values=null_markers)
        print(f"\nFile '{csv_name}' loaded successfully!")
        self._infer_and_correct_types()

    def _infer_and_correct_types(self):
        """Attempts to safely cast object columns to numeric formats where possible."""
        if self.data_frame is None: return

        for feature in self.data_frame.columns:
            # Coerce errors to NaN to see if the column can be treated as numeric
            num_cast = pd.to_numeric(self.data_frame[feature], errors='coerce')
            if not num_cast.isna().all():
                self.data_frame[feature] = num_cast

        # Categorize columns by their resolved data types
        self.num_fields = list(self.data_frame.select_dtypes(include=[np.number]).columns)
        self.cat_fields = list(self.data_frame.select_dtypes(exclude=[np.number]).columns)

    # === 2. DATASET AUDITING & SANITIZATION ===
    def print_dataset_overview(self):
        """Outputs the core dimensions, data types, and a brief snippet of the data."""
        if self.data_frame is None:
            print("Warning: No active dataset to summarize.")
            return
            
        print(f"Dimensions: {self.data_frame.shape[0]} total rows, {self.data_frame.shape[1]} total columns")
        print(f"Numeric Fields ({len(self.num_fields)}): {self.num_fields}")
        print(f"Categorical Fields ({len(self.cat_fields)}): {self.cat_fields}\n")
        print("--- Top 20 Records ---")
        display(self.data_frame.head(20))

    def resolve_missing_data(self, fill_technique='median', custom_val=None):
        """Addresses NaN values based on statistical measures or a static input."""
        if self.data_frame is None: return

        for feature in self.data_frame.columns:
            if self.data_frame[feature].isna().sum() == 0:
                continue # Skip complete columns

            if feature in self.num_fields:
                if fill_technique == 'mean':
                    self.data_frame[feature].fillna(self.data_frame[feature].mean(), inplace=True)
                elif fill_technique == 'median':
                    self.data_frame[feature].fillna(self.data_frame[feature].median(), inplace=True)
                elif fill_technique == 'mode':
                    self.data_frame[feature].fillna(self.data_frame[feature].mode()[0], inplace=True)
                elif fill_technique == 'constant' and custom_val is not None:
                    self.data_frame[feature].fillna(custom_val, inplace=True)
            else:
                # Non-numeric columns default to mode or the constant value
                cat_mode_val = self.data_frame[feature].mode()
                fallback = cat_mode_val[0] if not cat_mode_val.empty else "Unknown"
                self.data_frame[feature].fillna(fallback if fill_technique != 'constant' else custom_val, inplace=True)
                
        print(f"Executed null-imputation using the '{fill_technique}' method.")

    def drop_exact_duplicates(self):
        """Identifies and eliminates identical row entries."""
        if self.data_frame is not None:
            starting_row_count = self.data_frame.shape[0]
            self.data_frame.drop_duplicates(inplace=True)
            print(f"Cleared {starting_row_count - self.data_frame.shape[0]} duplicate records.")

    def filter_anomalies(self, target_cols=None, auto_remove=True):
        """Uses the Interquartile Range (IQR) to flag or strip outliers from numeric features."""
        if self.data_frame is None: return
        fields_to_scan = target_cols if target_cols else self.num_fields

        drop_indices = set()
        for feature in fields_to_scan:
            quartile_1 = self.data_frame[feature].quantile(0.25)
            quartile_3 = self.data_frame[feature].quantile(0.75)
            interquartile_range = quartile_3 - quartile_1
            lower_limit = quartile_1 - 1.5 * interquartile_range
            upper_limit = quartile_3 + 1.5 * interquartile_range

            anomaly_indices = self.data_frame[(self.data_frame[feature] < lower_limit) | (self.data_frame[feature] > upper_limit)].index
            
            if auto_remove:
                drop_indices.update(anomaly_indices)
            else:
                print(f"Feature '{feature}' contains {len(anomaly_indices)} potential outliers outside ({lower_limit:.2f}, {upper_limit:.2f})")

        if auto_remove and drop_indices:
            self.data_frame.drop(index=list(drop_indices), inplace=True)
            print(f"Purged {len(drop_indices)} records with detected anomalies.")

    def prompt_column_removal(self):
        """Requests user input to drop specific columns by name."""
        user_cols = input("Provide the exact names of columns to remove (comma-separated): ")
        cols_to_remove = [c.strip() for c in user_cols.split(',') if c.strip() in self.data_frame.columns]
        self.data_frame.drop(columns=cols_to_remove, inplace=True)
        self._infer_and_correct_types() # Re-evaluate fields
        print(f"Successfully dropped: {cols_to_remove}")

    def prompt_row_removal(self):
        """Requests user input to drop specific rows by their integer index."""
        user_rows = input("Provide row index numbers to remove (comma-separated): ")
        try:
            rows_to_remove = [int(r.strip()) for r in user_rows.split(',') if r.strip().isdigit()]
            self.data_frame.drop(index=rows_to_remove, inplace=True)
            print(f"Successfully dropped indices: {rows_to_remove}")
        except Exception as err:
            print(f"Failed to drop rows: {err}")

    # === 3. PREPROCESSING FOR MACHINE LEARNING ===
    def scale_numeric_features(self, scale_technique='standard'):
        """Applies normalization or standardization routines to numeric data."""
        if self.data_frame is None or not self.num_fields: return pd.DataFrame()

        if scale_technique == 'minmax':
            scaling_model = MinMaxScaler()
        elif scale_technique == 'robust':
            scaling_model = RobustScaler()
        else:
            scaling_model = StandardScaler()

        transformed_nums = scaling_model.fit_transform(self.data_frame[self.num_fields])
        return pd.DataFrame(transformed_nums, columns=self.num_fields, index=self.data_frame.index)

    def encode_categorical_features(self, encode_technique='onehot'):
        """Transforms text categories into machine-readable numeric structures."""
        if self.data_frame is None or not self.cat_fields: return pd.DataFrame()

        if encode_technique == 'onehot':
            encoding_model = OneHotEncoder(sparse_output=False, drop='first')
            transformed_cats = encoding_model.fit_transform(self.data_frame[self.cat_fields].astype(str))
            feature_labels = encoding_model.get_feature_names_out(self.cat_fields)
            return pd.DataFrame(transformed_cats, columns=feature_labels, index=self.data_frame.index)

        elif encode_technique in ['ordinal', 'uniform']:
            encoding_model = OrdinalEncoder()
            transformed_cats = encoding_model.fit_transform(self.data_frame[self.cat_fields].astype(str))
            encoded_df = pd.DataFrame(transformed_cats, columns=self.cat_fields, index=self.data_frame.index)
            
            if encode_technique == 'uniform':
                # Force values into a 0 to 1 range
                encoded_df = (encoded_df - encoded_df.min()) / (encoded_df.max() - encoded_df.min() + 1e-9)
            return encoded_df

    def build_ml_ready_matrix(self, num_scale_method='standard', cat_encode_method='onehot'):
        """Merges scaled numbers and encoded categories into a final dataset."""
        numeric_subset = self.scale_numeric_features(scale_technique=num_scale_method)
        categorical_subset = self.encode_categorical_features(encode_technique=cat_encode_method)
        return pd.concat([numeric_subset, categorical_subset], axis=1)

    # === 4. EXPLORATORY VISUALIZATION ENGINE ===
    def render_univariate_panels(self, feature_list):
        """Displays a combination of a violin plot, scatter plot, and histogram for continuous features."""
        for feature in feature_list:
            if feature not in self.num_fields: continue

            panel_fig = make_subplots(rows=1, cols=3, subplot_titles=('Violin Distribution', 'Scatter View', 'Density Histogram'))
            panel_fig.add_trace(go.Violin(x=self.data_frame[feature], box_visible=True, points='all', name=feature), row=1, col=1)
            panel_fig.add_trace(go.Scatter(y=self.data_frame[feature], mode='markers', marker=dict(opacity=0.6)), row=1, col=2)
            panel_fig.add_trace(go.Histogram(x=self.data_frame[feature]), row=1, col=3)

            panel_fig.update_layout(title_text=f"Feature Analysis: {feature}", showlegend=False, height=400)
            panel_fig.show()

    def render_bivariate_relationship(self, feature_x, feature_y):
        """Automatically chooses the best chart type based on the data types of the two inputs."""
        if feature_x not in self.data_frame.columns or feature_y not in self.data_frame.columns: return

        is_x_num = feature_x in self.num_fields
        is_y_num = feature_y in self.num_fields

        if is_x_num and is_y_num:
            # Both numeric: scatter with trendline
            relation_fig = px.scatter(self.data_frame, x=feature_x, y=feature_y, trendline="ols", title=f"Correlation View: {feature_x} & {feature_y}")
        elif not is_x_num and not is_y_num:
            # Both categorical: heatmap density
            relation_fig = px.density_heatmap(self.data_frame, x=feature_x, y=feature_y, text_auto=True, title=f"Categorical Overlap: {feature_x} & {feature_y}")
        else:
            # Mixed data types: Box plot distributions
            cat_axis = feature_x if not is_x_num else feature_y
            num_axis = feature_y if not is_x_num else feature_x
            relation_fig = px.box(self.data_frame, x=cat_axis, y=num_axis, points="all", title=f"Spread: {num_axis} segmented by {cat_axis}")
        
        relation_fig.show()

    # === 5. ADVANCED STATISTICAL PROFILING ===
    def render_global_correlation_map(self):
        """Computes and graphs an association grid supporting mixed data types (Pearson/Cramér's V)."""
        if self.data_frame is None: return
        feature_labels = self.data_frame.columns
        col_count = len(feature_labels)
        correlation_grid = pd.DataFrame(np.zeros((col_count, col_count)), index=feature_labels, columns=feature_labels)

        for col_a in feature_labels:
            for col_b in feature_labels:
                if col_a == col_b:
                    correlation_grid.loc[col_a, col_b] = 1.0
                elif col_a in self.num_fields and col_b in self.num_fields:
                    correlation_grid.loc[col_a, col_b] = self.data_frame[col_a].corr(self.data_frame[col_b], method='pearson')
                elif col_a in self.cat_fields and col_b in self.cat_fields:
                    # Cramér's V evaluation for categorical-categorical pairs
                    crosstab_matrix = pd.crosstab(self.data_frame[col_a], self.data_frame[col_b])
                    if crosstab_matrix.size > 0:
                        from scipy.stats import chi2_contingency
                        chi_sq_val = chi2_contingency(crosstab_matrix)[0]
                        total_obs = crosstab_matrix.sum().sum()
                        phi_sq = chi_sq_val / total_obs
                        row_len, col_len = crosstab_matrix.shape
                        phi_sq_corr = max(0, phi_sq - ((col_len-1)*(row_len-1))/(total_obs-1))
                        row_corr = row_len - ((row_len-1)**2)/(total_obs-1)
                        col_corr = col_len - ((col_len-1)**2)/(total_obs-1)
                        correlation_grid.loc[col_a, col_b] = np.sqrt(phi_sq_corr / min((col_corr-1), (row_corr-1))) if min((col_corr-1), (row_corr-1)) > 0 else 0
                else:
                    # Point-biserial approximation for mixed relationships
                    continuous_col = col_a if col_a in self.num_fields else col_b
                    discrete_col = col_b if col_a in self.num_fields else col_a
                    try:
                        numeric_codes = self.data_frame[discrete_col].astype('category').cat.codes
                        correlation_grid.loc[col_a, col_b] = self.data_frame[continuous_col].corr(numeric_codes)
                    except:
                        correlation_grid.loc[col_a, col_b] = 0.0

        heat_fig = px.imshow(correlation_grid, text_auto=".2f", color_continuous_scale='RdBu_r',
                             title="Full Feature Association Matrix")
        heat_fig.show()

    def mount_html_payload(self, visualization_payload):
        """Internal helper to inject raw HTML dicts created by VizEngine into the notebook."""
        if isinstance(visualization_payload, dict) and "html" in visualization_payload:
            from IPython.display import HTML
            display(HTML(visualization_payload["html"]))
        else:
            print("Payload rejected: Unrecognized format.")

class VizEngine:
    """ Manages modular plotting routines, returning pure HTML payloads for Colab embedding. """

    def __init__(self):
        pass

    def build_bar_chart(self, x_axis, y_axis, source_data, group_color=None, mode='group', chart_title=None):
        """Constructs a standard bar visualization and wraps it in a dictionary payload."""
        try:
            bar_fig = px.bar(source_data, x=x_axis, y=y_axis, color=group_color, barmode=mode, title=chart_title, text_auto=True)
            return {"status": "success", "html": bar_fig.to_html(include_plotlyjs='cdn', full_html=False)}
        except Exception as err:
            return {"status": "error", "message": str(err)}

    def build_donut_chart(self, label_col, value_col, source_data, center_hole=0.4, chart_title=None):
        """Designs a customized pie/donut layout with a transparent center hole."""
        try:
            donut_fig = px.pie(source_data, names=label_col, values=value_col, hole=center_hole, title=chart_title)
            return {"status": "success", "html": donut_fig.to_html(include_plotlyjs='cdn', full_html=False)}
        except Exception as err:
            return {"status": "error", "message": str(err)}

    def build_distribution_hist(self, target_axis, source_data, bin_params=None, chart_title=None):
        """Generates a density histogram, optionally mapping explicit interval bins."""
        try:
            hist_fig = px.histogram(source_data, x=target_axis, title=chart_title)
            if bin_params is not None:
                hist_fig.update_traces(xbins=dict(start=min(bin_params), end=max(bin_params), size=(max(bin_params)-min(bin_params))/len(bin_params)))
            return {"status": "success", "html": hist_fig.to_html(include_plotlyjs='cdn', full_html=False)}
        except Exception as err:
            return {"status": "error", "message": str(err)}

    def render_to_display(self, component_payload):
        """Takes a VizEngine success payload and forces it to render visually in the interface."""
        if component_payload.get("status") == "success":
            from IPython.display import HTML, display
            display(HTML(component_payload["html"]))
        else:
            print(f"Rendering Pipeline Failure: {component_payload.get('message')}")

# ==========================================
# EXECUTION & TESTING BLOCK
# ==========================================

# Spin up instance objects
refiner_instance = DataRefiner()
viz_instance = VizEngine()

# 1. Fetch external test data 
dataset_link = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
refiner_instance.data_frame = pd.read_csv(dataset_link)
refiner_instance._infer_and_correct_types() # Resolve structural types

# 2. View summary metadata
refiner_instance.print_dataset_overview()

# 3. Handle missing items and identical rows
refiner_instance.resolve_missing_data(fill_technique='median')
refiner_instance.drop_exact_duplicates()

# 4. Perform an audit for numeric outliers (flagging only)
refiner_instance.filter_anomalies(target_cols=['Age', 'Fare'], auto_remove=False)

# 5. Extract a processed dataset ideal for AI algorithms
final_matrix_df = refiner_instance.build_ml_ready_matrix(num_scale_method='robust', cat_encode_method='onehot')
print("\n--- Final ML Feature Matrix ---")
display(final_matrix_df.head(5))

# 6. Execute graphical profiling methods
refiner_instance.render_univariate_panels(['Age', 'Fare'])
refiner_instance.render_bivariate_relationship('Pclass', 'Fare')
refiner_instance.render_global_correlation_map()

# 7. Test standalone plotting class outputs
viz_payload = viz_instance.build_donut_chart(label_col='Sex', value_col='PassengerId', source_data=refiner_instance.data_frame, chart_title='Gender Proportion')
viz_instance.render_to_display(viz_payload)